apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-canary
spec:
  replicas: 4

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: leaddevops/kubeserve:v1
        ports:
        - containerPort: 80

  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: {}

      - setWeight: 50
      - pause: {}

      - setWeight: 75
      - pause: {}

      - setWeight: 100
